### ISSUE TITLE
bridge-no-bootopts-net failing on rhel8: "ERR anaconda:packaging: base repo (URL/http://download.eng.bos.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.10.0/compose/BaseOS/x86_64/os) not valid -- removing it"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1018]
since 2023-10-25

```
00:27:44,923 DEBUG anaconda:anaconda: network: NM not connected, waited 46 seconds
00:27:44,924 INFO anaconda:anaconda: threading: Thread Done: AnaWaitForConnectingNMThread (139783812396800)
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/13204585/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/13204587/virt-install.log)

Logs from s successful run in previous nightly:
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/13204643/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/13204644/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/1019

**Comment by jkonecny12** [comment]
@rvykydal the bug seems to be fixed now. Could we enable the test back?

**Comment by marusak** [comment]
> @rvykydal the bug seems to be fixed now. Could we enable the test back?

Still valid

**Comment by jstodola** [comment]
Since RHEL-8.10 will be the last RHEL-8 release, executing tests on RHEL-8 could be soon turned off completely.

**Comment by marusak** [comment]
Ok, closing. Let's stop testing on rhel8 soon.
