### ISSUE TITLE
rootpw-allow-ssh failing on rhel10 with "org.fedoraproject.Anaconda.Modules.Payloads:missing packages: sshpass"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1109]
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/14742381/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/14742382/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/1113

**Comment by marusak** [comment]
Fixed in https://github.com/rhinstaller/kickstart-tests/pull/1168
