### ISSUE TITLE
daily-iso boot.iso uses "fedora" profile while rawhide boot.iso uses "fedora-server"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1120]
While for our daily built iso (https://github.com/rhinstaller/kickstart-tests/actions/workflows/daily-boot-iso-rawhide.yml) the `fedora` profile is detected, for regular rawhide boot.iso test (https://github.com/rhinstaller/kickstart-tests/blob/17a749ac9b8887ad3936a895cf872c962e0dfe1d/containers/runner/launch#L115) `fedora-server` is the profile.

One consequence of it can be seen here: https://github.com/rhinstaller/kickstart-tests/pull/1116#issuecomment-2033780167

**Comment by rvykydal** [comment]
Seems that using Everything boot.iso (https://mirror.karneval.cz/pub/linux/fedora/linux/development/rawhide/Everything/x86_64/os/images/boot.iso) would result in 'fedora' profile.

**Comment by jstodola** [comment]
Nothing to do. Due to https://github.com/rhinstaller/kickstart-tests/pull/1123, both daily iso and rawhide use the `server` profile now. Closing after confirmation with @rvykydal .
