### ISSUE TITLE
204/209 tests failing on rhel10: "org.fedoraproject.Anaconda.Modules.Payloads:missing packages: kdump-utils"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1190]
https://issues.redhat.com/browse/RHEL-37138

**Comment by rvykydal** [comment]
anaconda-conf logs:
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/15375092/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/15375094/virt-install.log)

**Comment by rvykydal** [comment]
workaround for the issue, use "%packages --ignoremissing"

**Comment by jstodola** [comment]
This issue is fixed in RHEL-10.0-20240520.72.
