### ISSUE TITLE
proxy-cmdline fails (spuriously?) due to lack of .treeinfo request

### ISSUE THREAD

**Issue by AdamWill** [rhinstaller/kickstart-tests#12]
so working on my openQA kickstart-tests runner, the proxy-cmdline test fails with `.treeinfo request was not proxied`. However, when I run the test interactively to check on it, it seems like the proxying all works perfectly well - I can `tail -f /tmp/proxy.log` and see all sorts of other stuff get proxied, including the two other things the check would look for - but there just isn't a `.treeinfo` request, it seems.

anyone have ideas on this? is it a genuine bug the test is catching? is it something different in my config when run in openQA? is the test borked?

I'm running the test on F24 Alpha Server netinst for now, to reproduce just run an install with `inst.ks=https://www.happyassassin.net/ks/tests/proxy-cmdline.ks inst.proxy=http://127.0.0.1:8080` and poke around in `/tmp/proxy.log` while it's installing...you can see my parsed version of the kickstart at that URL. https://www.happyassassin.net/temp/proxy-cmdline.log is the proxy.log from a test run (after package download has completed, while install is running).

**Comment by AdamWill** [comment]
so we know what this is now: it's because I'm using a mirrorlist. we have a fix, just deciding how much more change to make to the proxy tests (if any) since I had some ideas.

**Comment by jkonecny12** [comment]
Is this issue still valid or it could be closed now?

**Comment by AdamWill** [comment]
I'm pretty sure https://github.com/rhinstaller/kickstart-tests/commit/847bce82eabed728bd0199d5bdb3e7ffa31f4786 would've fixed it.
