### ISSUE TITLE
rpm-ostree-container-luks failing on rhel10 with timeout

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#1293]
Started to appear 08/14/2024
There is no change in installer image package set compared to the previous successful run.
[kstest.log](https://github.com/user-attachments/files/16778226/kstest.log)
[virt-install.log](https://github.com/user-attachments/files/16778227/virt-install.log)

Maybe related to https://github.com/rhinstaller/kickstart-tests/issues/1250

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/1295

**Comment by jkonecny12** [comment]
Hmm, this is weird from the logs it seems the installation went just fine. Not sure what is happening there.

**Comment by jkonecny12** [comment]
Seems there is some progress on https://gitlab.com/fedora/bootc/base-images/-/issues/17
