### ISSUE TITLE
Create workflow for daily RHEL 8 + anaconda COPR boot.iso

### ISSUE THREAD

**Issue by martinpitt** [rhinstaller/kickstart-tests#427]
In the [rhel-daily-boot-iso branch](https://github.com/rhinstaller/kickstart-tests/commits/rhel-daily-boot-iso) I'm trying to provide a counterpart of the "Build daily Rawhide+COPR boot.iso" plus "daily-iso" scenario for RHEL. We already have the bit that builds the anaconda rhel8 branch into a COPR every night, but we don't use it for anything.

I did a [first run of this](https://github.com/rhinstaller/kickstart-tests/runs/1487947052?check_suite_focus=true), but it completely falls over because the generated image does not boot. After some struggling I found out how to debug this sensibly, with getting a serial console, debug info, and a shell. In the /var/tmp/kstest-* directory inside the container, I run this:

```
virt-install -n k --transient -r 2048 --rng /dev/random --noreboot --graphics none --initrd-inject /opt/kstest/kickstart-tests/container.ks --disk path=./disk-a.img,cache=unsafe,bus=sata --disk path=boot.iso,device=cdrom,readonly=on,shareable=on --extra-args 'inst.ks=file:/container.ks console=ttyS0,115200 rd.shell debug=1 inst.debug inst.kernel.hung_task_timeout_secs=1200 inst.stage2=hd:CDLABEL=RHEL-8-daily-x86_64' --location boot.iso,kernel=isolinux/vmlinuz,initrd=isolinux/initrd.img
```

boot.iso is the ISO that I built with this command, on a RHEL 8.3 or 8.4 nightly host (no difference between these);
```
sudo podman exec -w /data lorax lorax -p "Red Hat Enterprise Linux" \
     --version 8 --release 8 --variant=BaseOS --volid=RHEL-8-4-0-BaseOS-x86_64 --nomacboot \
     -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/ \
     -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/AppStream/x86_64/os/ \
     -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/CRB/x86_64/os/ \
     -s http://coprbe.devel.redhat.com/results/rhinstaller-group/Anaconda/rhel-8.dev-x86_64/ \
     /data/results
```

The boot fails when dracut tries to pivot to the live system:
```
         Starting Switch Root...
[FAILED] Failed to start Switch Root.
See 'systemctl status initrd-switch-root.service' for details.


# systemctl status initrd-switch-root |cat
● initrd-switch-root.service - Switch Root
   Loaded: loaded (/usr/lib/systemd/system/initrd-switch-root.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-12-03 10:00:28 UTC; 34s ago
  Process: 887 ExecStart=/usr/bin/systemctl --no-block switch-root /sysroot (code=exited, status=1/FAILURE)
 Main PID: 887 (code=exited, status=1/FAILURE)

systemctl[887]: Failed to switch root: Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
systemctl[887]: Bus n/a: changing state RUNNING → CLOSED
systemd[1]: initrd-switch-root.service: Child 887 belongs to initrd-switch-root.service.
systemd[1]: initrd-switch-root.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: initrd-switch-root.service: Failed with result 'exit-code'.
systemd[1]: initrd-switch-root.service: Changed start -> failed
systemd[1]: initrd-switch-root.service: Job initrd-switch-root.service/start finished, result=failed
systemd[1]: Failed to start Switch Root.
systemd[1]: initrd-switch-root.service: Unit entered failed state.
```

And that's true, /sysroot only contains a handful of files which are meant to customize the OS, but there's no actual OS.

In a [working boot](https://github.com/rhinstaller/kickstart-tests/files/5637547/84works.log), dracut does all the things that we expect, like
```
[   11.020509] dracut-cmdline[300]: ///lib/dracut/hooks/cmdline/27-parse-anaconda-repo.sh@8(source): stage2=hd:CDLABEL=RHEL-8-4-0-BaseOS-x86_64
[   11.023900] dracut-cmdline[300]: ///lib/dracut/hooks/cmdline/27-parse-anaconda-repo.sh@10(source): arg=repo
[   11.026749] dracut-cmdline[300]: ///lib/dracut/hooks/cmdline/27-parse-anaconda-repo.sh@12(source): '[' -n hd:CDLABEL=RHEL-8-4-0-BaseOS-x86_64 ']'
[   11.030038] dracut-cmdline[300]: ///lib/dracut/hooks/cmdline/27-parse-anaconda-repo.sh@12(source): arg=stage2
[   11.032878] dracut-cmdline[300]: ///lib/dracut/hooks/cmdline/27-parse-anaconda-repo.sh@12(source): repo=hd:CDLABEL=RHEL-8-4-0-BaseOS-x86_64
[   11.036248] dracut-cmdline[300]: ///lib/dracut/hooks/cmdline/27-parse-anaconda-repo.sh@15(source): rm -f /tmp/stage2_urls
[   11.040485] dracut-cmdline[300]: ///lib/dracut/hooks/cmdline/27-parse-anaconda-repo.sh@18(source): getargbool 0 inst.stage2.all
[...]
[   25.468956] dracut-initqueue[849]: + printf 'mount /dev/mapper/live-rw %s\n' /sysroot
[   25.469075] dracut-initqueue[849]: + run_checkisomd5 /dev/sr0
[   25.469124] dracut-initqueue[849]: + livedev=/dev/sr0
[...]
[   27.541131] dracut-mount[1185]: //lib/dracut/hooks/mount/01-945-anaconda.sh@1(source): mount /dev/mapper/live-rw /sysroot
[   27.695289] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)

```

But the [failing boot of the daily](https://github.com/rhinstaller/kickstart-tests/files/5637565/8dailyfails.log) does not do any of that. Instead, it crashes early on here:
```
[   10.658138] dracut-cmdline[289]: //lib/anaconda-lib.sh@279(parse_kickstart): /sbin/parse-kickstart /tmp/ks.cfg
[   10.662344] dracut-cmdline[289]: Traceback (most recent call last):
[   10.664717] dracut-cmdline[289]:   File "/sbin/parse-kickstart", line 37, in <module>
[   10.667665] dracut-cmdline[289]:     from pykickstart.parser import KickstartParser, preprocessKickstart
[   10.671163] dracut-cmdline[289]:   File "/usr/lib/python3.6/site-packages/pykickstart/parser.py", line 46, in <module>
[   10.676132] dracut-cmdline[289]:     from pykickstart import constants, version
[   10.678796] dracut-cmdline[289]:   File "/usr/lib/python3.6/site-packages/pykickstart/version.py", line 55, in <module>
[   10.682980] dracut-cmdline[289]:     from pykickstart.load import load_to_str
[   10.686527] dracut-cmdline[289]:   File "/usr/lib/python3.6/site-packages/pykickstart/load.py", line 20, in <module>
[   10.691495] dracut-cmdline[289]:     import requests
[   10.694174] dracut-cmdline[289]:   File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
[   10.698293] dracut-cmdline[289]:     import urllib3
[   10.700988] dracut-cmdline[289]:   File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
[   10.705421] dracut-cmdline[289]:     from .connectionpool import (
[   10.708209] dracut-cmdline[289]:   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
[   10.711969] dracut-cmdline[289]:     from .exceptions import (
[   10.715190] dracut-cmdline[289]:   File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
[   10.718784] dracut-cmdline[289]:     from .packages.six.moves.http_client import (
[   10.722582] dracut-cmdline[289]: ModuleNotFoundError: No module named 'urllib3.packages.six'
```

There is [precedent](https://github.com/urllib3/urllib3/issues/1518) which suggests that the `python3-six` module is somehow not installed correctly, but I don't yet know how to validate this. Maybe someone sees a hint in the linked verbose logs?

One thing that's worth mentioning is that my self-built iso is 67 MB, while the "official" nightly build is 75 MB -- so maybe the image is somehow damaged, and lorax didn't complain?

FTR, I tried to run lorax in the RHEL 8.3 version and 8.4 nightly on the host, there's no difference.

**Comment by martinpitt** [comment]
@jkonecny12 , @rvykydal : I created this as a brain dump and place where to collect debugging notes and logs. I think I'll postpone this and concentrate on the other tasks first, but I suppose some day someone wants to pick this up again. I didn't yet want to create a PR, as that keeps involving Travis runs, and it's too early for that.

**Comment by jkonecny12** [comment]
OK, thanks for all the info. I hope I'll find some time to look on what is going on there. Maybe I could spot something.

**Comment by jstodola** [comment]
Hi @martinpitt , 67 MB or 75 MB is way too low for an iso, so I wonder what file do you mean? For example just the installation initrd from RHEL-8.3 GA has ~70 MB and boot.iso ~680 MB.

I tried to run your lorax command on an RHEL-8 system (not using podman) and it produced an usable boot.iso (687 MB, and 72 MB initrd.img)

What might be a problem is that lorax was executed with `--volid=RHEL-8-4-0-BaseOS-x86_64`, but the VM was booted with `inst.stage2=hd:CDLABEL=RHEL-8-daily-x86_64`. Can you try `inst.stage2=hd:CDLABEL=RHEL-8-4-0-BaseOS-x86_64` instead?

It could also help to see the logs from lorax. There might be a problem with loop devices inside a container for example.

**Comment by martinpitt** [comment]
Hello jstodola,

your comment somehow didn't make it to the GitHub web UI, so fullquote here.

jstodola [2020-12-04 15:12 -0800]:
> Hi @martinpitt , 67 MB or 75 MB is way too low for an iso, so I wonder what file do you mean? For example just the installation initrd from RHEL-8.3 GA has ~70 MB and boot.iso ~680 MB.

Sorry, I mis-looked. I meant 670 MB (self-built) vs. 750 MB (official) of
course.

> I tried to run your lorax command on an RHEL-8 system (not using podman) and it produced an usable boot.iso (687 MB, and 72 MB initrd.img)

Interesting, so that is slightly bigger than the one I built, but also way
smaller than the official one.

> What might be a problem is that lorax was executed with `--volid=RHEL-8-4-0-BaseOS-x86_64`, but the VM was booted with `inst.stage2=hd:CDLABEL=RHEL-8-daily-x86_64`. Can you try `inst.stage2=hd:CDLABEL=RHEL-8-4-0-BaseOS-x86_64` instead?

My self-built one really does have that label, on purpose -- I don't want to
make it appear like an official one. I did try a different label, but that's
not it.

> It could also help to see the logs from lorax. There might be a problem with loop devices inside a container for example.

Right, loop devices are a bit tricky. The container runs privileged and gets
loop0 and loop-control from the host. I also tried to create and pass loop1 in
addition, but no difference.

Image build logs are in the artifacts of the run. [direct link](https://github.com/rhinstaller/kickstart-tests/suites/1597505955/artifacts/29106073)

**Comment by martinpitt** [comment]
Curiously I'm running into the exact same issue when trying to build a Rawhide boot.iso on Rawhide [here](https://github.com/martinpitt/anaconda/commit/14eeb3d158d02079789f3717678efe57e3d710df#diff-417e91a71b4bed5fa74bff0c8b746144018f57fba183d1740f1f6763653d0235R128). But the same lorax command (minus the COPRs) works in our [daily-boot-iso.yml](https://github.com/rhinstaller/kickstart-tests/blob/master/.github/workflows/daily-boot-iso.yml#L22) workflow; that's also using a fedora:rawhide container as lorax' host. The only difference is that the latter runs on Ubuntu with docker, while the former runs on Fedora with podman.

:exploding_head:

**Comment by martinpitt** [comment]
I finally found a relatively small standalone reproducer for investigating this, and reported https://bugzilla.redhat.com/show_bug.cgi?id=1906364 for this.

**Comment by martinpitt** [comment]
Found a workaround :partying_face: , so I'll resume this. it worked fine for [anaconda's kickstart-test runs](https://github.com/rhinstaller/anaconda/pull/3047).
