### ISSUE TITLE
network naming confusion on RHEL daily boot.iso

### ISSUE THREAD

**Issue by martinpitt** [rhinstaller/kickstart-tests#448]
Four network+coverage tests consistently fail on the [RHEL 8 daily scenario](https://github.com/rhinstaller/kickstart-tests/actions?query=workflow%3A%22Build+and+test+daily+RHEL+boot.iso%22):
```
onboot-activate                                         | FAILED     | error in log: packaging: base repo (URL/http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/) not valid -- removing it
team-pre                                                | FAILED     | error in log: packaging: base repo (URL/http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/) not valid -- removing it
network-static-2-httpks                                 | TIMED OUT  | 
bond2-httpks                                            | TIMED OUT  | 
```

When following along onboot-activate with virt-viewer, the installer shows the network device configuration screen without further progress, i.e. the kickstart does not match the available devices. 

This is because our tests ordinarily expect network device names `enpNs0`, but on the RHEL daily we have the `ens*`  pattern instead:
```
03:26:20,515 NOTICE xserver:[   304.498] Kernel command line: inst.ks=file:/onboot-activate.ks debug=1 inst.debug rd.shell=0 rd.emergency=poweroff ip=enp1s0:dhcp inst.kernel.hung_task_timeout_secs=1200 inst.stage2=hd:CDLABEL=RHEL-8-daily-0-BaseOS-x86_64
03:26:05,425 DEBUG anaconda:anaconda: network: Devices found: ['ens3', 'ens4', 'ens5']
```

and anaconda can't find the `enp*` ones:

```
03:26:06,495 WARNING org.fedoraproject.Anaconda.Modules.Network:DEBUG:anaconda.modules.network.nm_client:kickstart specification --device=enp2s0 ->  ()
03:26:06,495 WARNING org.fedoraproject.Anaconda.Modules.Network:WARNING:anaconda.modules.network.initialization:Apply kickstart: --device enp2s0 not found
03:26:06,495 WARNING org.fedoraproject.Anaconda.Modules.Network:DEBUG:anaconda.modules.network.nm_client:kickstart specification --device=enp1s0 ->  ()
03:26:06,496 WARNING org.fedoraproject.Anaconda.Modules.Network:WARNING:anaconda.modules.network.initialization:Apply kickstart: --device enp1s0 not found
03:26:06,496 WARNING org.fedoraproject.Anaconda.Modules.Network:DEBUG:anaconda.modules.network.nm_client:kickstart specification --device=enp3s0 ->  ()
03:26:06,496 WARNING org.fedoraproject.Anaconda.Modules.Network:WARNING:anaconda.modules.network.initialization:Apply kickstart: --device enp3s0 not found
```

This seems to work fine for the official rhel8 boot.iso, so I wonder if that's some difference in calling lorax? Or did the anaconda rhel8 branch recently get some networking name related changes?

**Comment by martinpitt** [comment]
I verified that changing the network device names to the ens* pattern works, the tests succeed with this local change:
```diff
--- network-device-names.cfg
+++ network-device-names.cfg
@@ -1,9 +1,9 @@
 NETDEV_PREFIX="enp"
 NETDEV_SUFFIX="s0"
-export KSTEST_NETDEV1=${NETDEV_PREFIX}1${NETDEV_SUFFIX}
-export KSTEST_NETDEV2=${NETDEV_PREFIX}2${NETDEV_SUFFIX}
-export KSTEST_NETDEV3=${NETDEV_PREFIX}3${NETDEV_SUFFIX}
-export KSTEST_NETDEV4=${NETDEV_PREFIX}4${NETDEV_SUFFIX}
-export KSTEST_NETDEV5=${NETDEV_PREFIX}5${NETDEV_SUFFIX}
-export KSTEST_NETDEV6=${NETDEV_PREFIX}6${NETDEV_SUFFIX}
+export KSTEST_NETDEV1=ens3
+export KSTEST_NETDEV2=ens4
+export KSTEST_NETDEV3=ens5
+export KSTEST_NETDEV4=ens6
+export KSTEST_NETDEV5=ens7
+export KSTEST_NETDEV6=ens8
```

To compare, I ran the test on the official RHEL 8 iso, and there the network names are indeed `enp1s0`. On that image, there is on `ID_NET_NAME_SLOT` at all in the udev device name database. udev is version 239-43.el8

On the self-built daily one, both `_SLOT` and `_PATH` exists, and as `_SLOT` has the higher priority it wins. udev is the same version here.

**Comment by martinpitt** [comment]
I asked @bcl and rhel-devel@ about how the official images are being built, so that we can reproduce this in our nightly boot.iso job.

**Comment by martinpitt** [comment]
I sent PR #449 to work around this for now, by just using the slot based names for the time being. Whenever we adjust the lorax invocation in the workflow, we can switch back to the path based names  again.

**Comment by VladimirSlavik** [comment]
For networking things, @rvykydal is your person...

**Comment by martinpitt** [comment]
Complete copy&pasteable reproducer from scratch (needs RH VPN):
```
sudo podman run --rm -it --tmpfs /var/tmp:rw,mode=1777  --privileged --device /dev/loop0 --device /dev/loop-control --device /dev/kvm --network host registry.access.redhat.com/ubi8
```

Inside the container:
```
unalias rm
rm /etc/yum.repos.d/*
cat <<EOR > /etc/yum.repos.d/rhel8.repo
[RHEL-8-BaseOS]
name=baseos
baseurl=http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/
enabled=1
gpgcheck=0
install_weak_deps=0
module_hotfixes=1

[RHEL-8-AppStream]
name=appstream
baseurl=http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/AppStream/x86_64/os/
enabled=1
gpgcheck=0
install_weak_deps=0
module_hotfixes=1
EOR

dnf install -y lorax qemu-img virt-install libvirt qemu-kvm
useradd user
mkdir /build
```

In the same root shell, build an image with lorax. This can be repeated several times with variations:
```
rm -rf /build/results
lorax -p "Red Hat Enterprise Linux" \
   --version 8 --release 8 --variant=BaseOS --volid=RHEL-8-daily-0-BaseOS-x86_64 --nomacboot \
   -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/ \
   -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/AppStream/x86_64/os/ \
   -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/CRB/x86_64/os/ \
   /build/results
```

For test-booting the image, find the running container name (`sudo podman ps`) and enter it as user:
```
sudo podman exec -it -u user CONTAINERNAME bash
```

Boot the generated image in that with
```
qemu-img create -f qcow2 disk-a.img 10G
echo text > test.ks
virt-install -n test --transient -r 2048 --rng /dev/random --noreboot --graphics none --disk path=./disk-a.img,cache=unsafe,bus=sata --disk path=/build/results/images/boot.iso,device=cdrom,readonly=on,shareable=on --initrd-inject test.ks --extra-args 'console=ttyS0,115200 rd.shell debug inst.ks=file:/test.ks inst.debug inst.stage2=hd:CDLABEL=RHEL-8-daily-0-BaseOS-x86_64' --location /build/results/images/boot.iso,kernel=isolinux/vmlinuz,initrd=isolinux/initrd.img
```
Wait until you see the "Starting installer" screen, press Alt-Tab to get to a shell, and check device names with `ip a`:
```
2: ens2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:9c:b1:10 brd ff:ff:ff:ff:ff:ff
```

You can exit the console with Control-] and then delete the running vm with `virsh destroy test`.

To compare with the official image, download and boot that:
```
curl -L http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/images/boot.iso --output r8.iso
virt-install -n test --transient -r 2048 --rng /dev/random --noreboot --graphics none --disk path=./disk-a.img,cache=unsafe,bus=sata --disk path=./r8.iso,device=cdrom,readonly=on,shareable=on --initrd-inject test.ks --extra-args 'console=ttyS0,115200 rd.shell debug inst.ks=file:/test.ks inst.debug inst.stage2=hd:CDLABEL=RHEL-8-4-0-BaseOS-x86_64' --location ./r8.iso,kernel=isolinux/vmlinuz,initrd=isolinux/initrd.img
```
Here device names look like this:
```
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:f9:28:d5 brd ff:ff:ff:ff:ff:ff
```

**Comment by martinpitt** [comment]
Debugging notes:

 - @bcl suggested that this may be because it's using the default instead of the rhel template. But `lorax-templates-rhel` gets [installed](https://github.com/rhinstaller/kickstart-tests/runs/1554572119?check_suite_focus=true#step:4:85) and  [used](https://github.com/rhinstaller/kickstart-tests/runs/1554572119?check_suite_focus=true#step:4:393), so that's not it.

 - I used the exact same `--version`, `--release`, and `--volid` values as the [official build](http://download-ipv4.eng.brq.redhat.com/nightly/latest-RHEL-8/logs/x86_64/buildinstall-BaseOS.x86_64.log):
```
lorax -p "Red Hat Enterprise Linux" --version 8.4 --release 8.4 --variant=BaseOS --volid=RHEL-8-4-0-BaseOS-x86_64 --nomacboot  --buildarch=x86_64  -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/    -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/AppStream/x86_64/os/    -s http://download.devel.redhat.com/nightly/rhel-8/RHEL-8/latest-RHEL-8/compose/CRB/x86_64/os/    /build/results
```
   Note that you have to adjust the `inst.stage2=` label accordingly. And lo and behold, I get "enp1s0"!

 - I don't like hardcoding the "8.4" (we'd have to bump it every 6 months and not forget about it). So I bisected the changed options, and it is really the `--volid` label that makes the difference. (What sense does that make??) `RHEL-8-daily-0-BaseOS-x86_64` somehow enables the "ens*" slot based names, while `RHEL-8-4-0-BaseOS-x86_64` disables them and uses the path based ones.

 - I tried with `--volid=RHEL-8-0-0-BaseOS-x86_64` and that works also. This at least avoids hardcoding the minor release.

 - I tried with `--volid=RHEL-8-D-0-BaseOS-x86_64` and that also fails (i.e. uses ens*). It really seems *something* expects a number in exactly that place of the volume label.

But *shrug*, enough dwelling on this. I'll send a PR that uses "8-0-0".

**Comment by bcl** [comment]
Ah! What if you run virt-install with `--os-variant detect=off`? I'm going to bet that you will get consistent results. I think virt-install is testing the volume name and switching its config based on it.

**Comment by martinpitt** [comment]
Thanks @bcl, that sounds like a reasonable explanation! For my successors in the anaconda team: I did *not* try that, as I'd rather stay close to how "real" RHEL images look like, instead of fine-tuning virt-install. (Also,  PTO..)

**Comment by VladimirSlavik** [comment]
For (my) future reference, the place to change the `virt-install` options is roughly here: https://github.com/rhinstaller/kickstart-tests/blob/master/scripts/launcher/lib/virtual_controller.py#L104
