### ISSUE TITLE
Limit the number of VMs running in parallel based on memory

### ISSUE THREAD

**Issue by jstodola** [rhinstaller/kickstart-tests#524]
The number of simultaneously executed VMs is currently limited by the number of processors:
https://github.com/rhinstaller/kickstart-tests/blob/master/containers/runner/launch#L10

This logic should take into account also the available amount of memory and reduce the number of VMs running at the same time.
(For example, a system with 64 CPUs and 16 GiB of memory cannot run 64 VMs at the same time).

**Comment by rvykydal** [comment]
https://github.com/rhinstaller/kickstart-tests/pull/525 has been merged.
