### ISSUE TITLE
Tests with check after reboot (--wait) are not killed by log monitor on traceback or timeout.

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#527]
Tests that are doing checks after reboot of installed system are not killed by LogMonitor on traceback and even worse on timeout (which makes daily builds to be killed by github workflout timeout without getting any logs and results). The tests:
```
reboot
reboot-initial-setup-tui
reboot-initial-setup-gui
```
set additional runner argument `--wait`:
https://github.com/rhinstaller/kickstart-tests/blob/edc124e78386303b33656e38de4d8ffdb6bd8753/reboot.sh#L23
which seems to be the cause of the problem.

One possible fix would be to set the argument to --wait (in minutes) to the default timeout. It could be somehow combined with https://github.com/rhinstaller/kickstart-tests/pull/504, eg by setting the default timeout in functions.sh variable.

**Comment by poncovka** [comment]
Fixed in https://github.com/rhinstaller/kickstart-tests/pull/535.
