### ISSUE TITLE
README file should be adjusted

### ISSUE THREAD

**Issue by jkonecny12** [rhinstaller/kickstart-tests#614]
We still have parts about `linchpin` and `ansible` in the main README file. This is not applicable after https://github.com/rhinstaller/kickstart-tests/pull/453 was merged. We should cleanup the top-level README file.

**Comment by VladimirSlavik** [comment]
It seems there is just one line that is not relevant anymore:

> Tooling for running tests on remote hosts is in linchpin_ and ansible_.

I think removing all of the docs would be wrong, what happens inside the container needs to be documented somehow too. Maybe split the internals off to another document and put it into `docs/`.

**Comment by jkonecny12** [comment]
OK, on the other hand it would be nice to more promote the `./containers/runner/README.md` which contains more useful information.

**Comment by VladimirSlavik** [comment]
Yes, definitely. If this works for you, I would split the file and make the container-oriented parts the default readme, while keeping the rest.

**Comment by jkonecny12** [comment]
Seems like a good idea to me. However, no-one else had a comment here.
