### ISSUE TITLE
daily-iso tests failing massively with new kernel: kernel NULL pointer dereference, address: 0000000000000018

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#618]
Reported here: https://bugzilla.redhat.com/show_bug.cgi?id=2020438
Workaround: use VGA driver: "--virtio vga"

**Comment by rvykydal** [comment]
PR with temporary workaround: https://github.com/rhinstaller/kickstart-tests/pull/619

**Comment by jkonecny12** [comment]
Do we want to leave this open as reminder or what is the plan here?

**Comment by rvykydal** [comment]
The BZ is fixed, PR to revert the workaround: https://github.com/rhinstaller/kickstart-tests/pull/631
