### ISSUE TITLE
authselect-not-set failing on daily-iso with "*** Failed check: authselect not installed or no existing configuration detected"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#640]
The authselect-not-set test is failing for daily-iso scenario with
```
stdout:
*** Failed check: authselect not installed or no existing configuration detected

2021-12-30 04:47:11,412 INFO: RESULT:authselect-not-set:a60e7dc23a91:FAILED:Validation failed with return code 1
```
Started to appear on Daily run #413 (https://github.com/rhinstaller/kickstart-tests/actions/runs/1635654206)
Attaching test logs from the first failing run #413:
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/7801393/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/7801395/virt-install.log)

Logs from the last successful run #412:
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/7801400/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/7801401/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/643

**Comment by poncovka** [comment]
It looks like `authselect` is installed and configured by default now.

```
> authselect current
Profile ID: sssd
Enabled features:
- with-silent-lastlog
```
