### ISSUE TITLE
module-1 and module-4 failing for daily-iso: ValidationReport(error_messages=[], warning_messages=['Some packages, groups or modules are missing.\n\nProblems in request:\nmissing groups or modules: @postgresql:14'])

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#669]
module-1 and module-4 tests are failing on daily-iso since Daily run Daily run #462 (https://github.com/rhinstaller/kickstart-tests/actions/runs/1855691287)

```
00:41:07,900 DEBUG anaconda:anaconda: modules.payloads.payload.dnf.dnf_manager: Resolving the software selection.
00:41:08,154 INFO anaconda:anaconda: modules.payloads.payload.dnf.dnf_manager: The software selection has been resolved (330 packages selected).
00:41:08,155 DEBUG anaconda:anaconda: modules.payloads.payload.dnf.validation: Resolving has been completed: ValidationReport(error_messages=[], warning_messages=['Some packages, groups or modules are missing.\n\nProblems in request:\nmissing groups or modules: @postgresql:14'])
00:41:08,156 WARNING anaconda:anaconda: modules.payloads.payload.dnf.installation: The packages were resolved with warnings:#012#012Some packages, groups or modules are missing.#012#012Problems in request:#012missing groups or modules: @postgresql:14
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/8086414/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/8086415/virt-install.log)

**Comment by rvykydal** [comment]
Seems to be as another iteration of this issue: https://github.com/rhinstaller/kickstart-tests/issues/575.
Maybe we should think about stability of the test. Create test with artificial modules or tag the test into some less stable tier (which we don't have yet).

**Comment by VladimirSlavik** [comment]
Indeed. I spoke with @jstodola a few weeks back and he offered some standard repo that RTT uses. That's internal, but the [rpm] repo definition is in a [git] repo. So perhaps we could use that.

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/673

**Comment by rvykydal** [comment]
Sounds interesting @VladimirSlavik , I've created https://github.com/rhinstaller/kickstart-tests/issues/674 to track it.

**Comment by poncovka** [comment]
There are only three modules in the Rawhide Modular repository. What is the actual status of this technology? Isn't it going to be deprecated? @M4rtinK?

**Comment by VladimirSlavik** [comment]
We would need the test for RHEL anyway.
