### ISSUE TITLE
Deal with instability of module-x tests

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#674]
Using real modules has tests maintenance costs:
https://github.com/rhinstaller/kickstart-tests/issues/575
https://github.com/rhinstaller/kickstart-tests/issues/669
https://github.com/rhinstaller/kickstart-tests/issues/658

We should try to make the modules more stable or move them to unstable tier, see
https://github.com/rhinstaller/kickstart-tests/issues/669#issuecomment-1042649522

**Comment by jstodola** [comment]
Just a note that there is a testing repository with modules used for downstream RHEL testing. Ping me or anyone from RTT on IRC.

**Comment by poncovka** [comment]
Based on a very quick research, it should be enough to define the testing modules with some yaml files generated in our `generate-repository.py` script. The `createrepo` tool should be able to handle the rest. See: https://bugzilla.redhat.com/show_bug.cgi?id=1795936

**Comment by poncovka** [comment]
Based on a discussion with the DNF team, it is worth it to create and use fake modules for testing.

**Comment by rvykydal** [comment]
Another iteration of the issue: https://github.com/rhinstaller/kickstart-tests/pull/770

**Comment by KKoukiou** [comment]
We disabled modularity tests also for Fedora, as the module feature is deprecated on RHEL-10 and Fedora-40.
