### ISSUE TITLE
[weekly reports] Sometimes details on flakes cotain also the successful run result which is redundant

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#711]
I noticed that sometimes (in most of the cases) the details on flakes contain both the failure detail (which is ok) and the following success detail (which is not useful). For example in this run:
https://github.com/rvykydal/kickstart-tests/actions/runs/2206406340
there are both details for most of the flakes, but only failure deatil for `ifname-httpks`

**Comment by bcl** [comment]
That was on purpose, but I guess I can remove them if you want. But first I'm curious as to why they are missing from some of those, every flake should have a success since that's how it is detected :)

**Comment by bcl** [comment]
It ends up this depends on the order it finds the test results in. If it finds the success first, then the failure it adds just the failure to the flake dict. If it finds the failure then the success it moves the failure to flakes and then appends the success to the flakes entry. I've added a commit to fix this, so flakes will only have the failed run listed.
