### ISSUE TITLE
fedora-live-image-build test failing with Module or Group 'x86-baremetal-tools' is not available

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#740]
Since the daily https://github.com/rhinstaller/kickstart-tests/actions/runs/2512314781 the fedora-live-image-build test is failing with timeout and these messages in the log:
```
03:23:44,301 ERR anaconda:dnf: no group 'arm-tools' from environment 'workstation-product-environment'
```
```
03:24:00,342 ERR anaconda:dnf: Module or Group 'x86-baremetal-tools' is not available.
03:24:00,343 ERR anaconda:anaconda: modules.payloads.payload.dnf.dnf_manager: Failed to apply specs!#012Problems in request:#012missing groups or modules: @x86-baremetal-tools
```

```
03:23:46,362 DEBUG anaconda:anaconda: ui.gui.spokes.software_selection: The selection has been checked: ValidationReport(error_messages=[], warning_messages=['Some packages, groups or modules are missing.\n\nProblems in request:\nmissing groups or modules: @x86-baremetal-tools'])
```

[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/8927685/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/8927686/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/741

**Comment by bcl** [comment]
This is likely related to the current attempt to switch to grub2 only on the boot.iso, comps commit that removes the x86-baremetal-tools  is here:

https://pagure.io/fedora-comps/c/d8fdba32ba2ded8d1cfacf8dcaa8bef089ad7adf?branch=main

**Comment by rvykydal** [comment]
Thank you for the pointer!
