### ISSUE TITLE
Kernel Call Trace in log monitor makes daily-iso tests less stable.

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#768]
Often the Call Trace is non-fatal but all tests in run fail because of detection of it in log monitor.

Examples:
https://github.com/rhinstaller/kickstart-tests/issues/698
https://github.com/rhinstaller/kickstart-tests/pull/762

Maybe we should consider disabling the detection for good.

**Comment by poncovka** [comment]
Let's do that. It just makes the test maintenance harder.

**Comment by rvykydal** [comment]
> Let's do that. It just makes the test maintenance harder.

https://github.com/rhinstaller/kickstart-tests/pull/771

**Comment by rvykydal** [comment]
Done
