### ISSUE TITLE
raid-ddf failing on rhel8 because the change is not in 8.8 yet

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#799]
Needs https://bugzilla.redhat.com/show_bug.cgi?id=2063791
which means python-blivet-3.4.0-13.el8

**Comment by rvykydal** [comment]
PR to disable the test: https://github.com/rhinstaller/kickstart-tests/pull/800

**Comment by jkonecny12** [comment]
Seems that this could be solved:
``<snip>/rhel-8/nightly/AppStream/x86_64/os/Packages/python3-blivet-3.4.0-13.el8.noarch.rpm``

**Comment by rvykydal** [comment]
Fixed although we are seeing a flake.
