### ISSUE TITLE
rhel-9 tests massively fail on OSCAP spoke failure: "RuntimeError: Expected a file /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml ..."

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#828]
Seems the https://github.com/rhinstaller/kickstart-tests/issues/827 hits also RHEL 9.
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/10102847/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10102850/virt-install.log)

**Comment by poncovka** [comment]
I've pinged the OSCAP team about that. The fix seems to be merged, so we just need a new build.

**Comment by rvykydal** [comment]
Disappeared as of https://github.com/rhinstaller/kickstart-tests/actions/runs/3587917333
