### ISSUE TITLE
packages-weakdeps failing on rhel8 with "ERR anaconda:dnf: Error in POSTIN scriptlet in rpm package insights-client"

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#830]
```
23:37:39,665 INFO anaconda:packaging: Configuring (running scriptlet for): insights-client-3.1.7-11.el8.noarch 1668185030 bc7487b118579b150c445d9d531abf569b2f16a68e302c96c2cc423d20d897db
23:37:40,376 INFO anaconda:dnf: ValueError: SELinux policy is not managed or store cannot be accessed.#012warning: %post(insights-client-0:3.1.7-11.el8.noarch) scriptlet failed, exit status 1
23:37:40,379 ERR anaconda:dnf: Error in POSTIN scriptlet in rpm package insights-client
```
[kstest.log](https://github.com/rhinstaller/kickstart-tests/files/10103704/kstest.log)
[virt-install.log](https://github.com/rhinstaller/kickstart-tests/files/10103705/virt-install.log)

**Comment by rvykydal** [comment]
PR to disable tests: https://github.com/rhinstaller/kickstart-tests/pull/832

**Comment by rvykydal** [comment]
Seems to have disappeared: https://github.com/rhinstaller/kickstart-tests/pull/834

**Comment by jstodola** [comment]
Reported as https://bugzilla.redhat.com/show_bug.cgi?id=2150908

**Comment by rvykydal** [comment]
> Seems to have disappeared: #834

Not, true, the local test suffered from https://github.com/rhinstaller/kickstart-tests/pull/836.

So disabling again: https://github.com/rhinstaller/kickstart-tests/pull/837
