### ISSUE TITLE
Prevent shellcheck warnings for missing shebang and TESTTYPE definition.

### ISSUE THREAD

**Issue by rvykydal** [rhinstaller/kickstart-tests#853]
For example as in this PR: https://github.com/rhinstaller/kickstart-tests/pull/850
where it was handled by adding the shebang and disabling the checks in the test.
We need a general solution for these warnings.

**Comment by VladimirSlavik** [comment]
Is adding the shebangs ok?

**Comment by rvykydal** [comment]
> Is adding the shebangs ok?
> 
> I expect that all the actual results would start pouring out after this.

I think so, let's add them. Or we can use "SHELLCHECK_OPTS -s bash" as in https://github.com/rhinstaller/kickstart-tests/pull/855

**Comment by rvykydal** [comment]
For the TESTTYPE we agreed on adding a comment and disabling locally for each test. I'd suggest:
https://github.com/rvykydal/kickstart-tests/blob/f1348ef2602317a26a2b89cd41a3c594dd251ccb/stage2-from-ks.sh#L20

**Comment by rvykydal** [comment]
> For the TESTTYPE we agreed on adding a comment and disabling locally for each test. I'd suggest: https://github.com/rvykydal/kickstart-tests/blob/f1348ef2602317a26a2b89cd41a3c594dd251ccb/stage2-from-ks.sh#L20

https://github.com/rhinstaller/kickstart-tests/pull/862
